### ISSUE TITLE
Unacceptable audience in id_token: GoogleSignIn library

### ISSUE THREAD

**Issue by ActuallyTaylor** [supabase/supabase-swift#221] opened 2024-01-18 01:25 UTC
# Bug report
## Describe the bug

I have implemented the GoogleSignIn library for my application to retrieve data from the user's Gmail account. I would like to continue using the GoogleSignIn library in my app, but I also want to implement Supabase google authentication. Whenever I go to sign in the user using their `idToken` and `accessToken` I get the following error:
```
Unacceptable audience in id_token Auth.AuthError.api(Auth.AuthError.APIError(msg: nil, code: nil, error: Optional("invalid request"), errorDescription: Optional("Unacceptable audience in id_token"), weakPassword: nil))
```

I have checked my Supabase console and I am placing my iOS app's bundle ID into "Authorized Client IDs" which seems to only be for Android. Do I need to place this into the ClientID? If so what would my secret be in this situation.

## Additional context

I have the following code (condensed) which authenticates the user first with GoogleSignIn. It then takes the user object and takes the `idToken` as well `accessToken` and provides them to Supabase's `signInWithIdToken` function.

```swift
let result = try await GIDSignIn.sharedInstance.signIn(withPresenting: window, hint: nil)
        
let user = result.user

guard let idToken = user.idToken?.tokenString else {
	return
}

try await supabase.auth.signInWithIdToken(
    credentials: .init(
        provider: .google,
        idToken: idToken,
        accessToken: user.accessToken.tokenString
    )
)
```

**Comment by dshukertjr** [comment] 2024-05-23 23:36
@ActuallyTaylor The error most likely means that you didn't set the web client ID in your Supabase dashboard. Google uses web client ID to verify the token instead of the iOS client ID, so although you do need to create the iOS client ID as well, you do need to create the web client ID in addition to it, [add it your application](https://developers.google.com/identity/sign-in/ios/start-integrating#add_client_id) and add it to the Supabase dashboard.

**Comment by Objy-marcus** [comment] 2024-05-29 23:14
I believe I have the same issue here, and the core of it is in this sentence from OP: _I would like to continue using the GoogleSignIn library in my app, but I also want to implement Supabase google authentication_


Using the example from @grdsdev with GoogleSignIn works well, you need to make sure your swift project or GoogleSignIn configuration is using an iOS OAuth 2.0 Client IDs from your Google Cloud console. I am following that example and it's code and it works. 

One point to add is that when using GoogleSignIn I have found I need to put the  iOS OAuth 2.0 Client IDs from your Google Cloud console into the Client ID (for OAuth) on the Supabase Dashboard > Authentication > Providers. _**Is this expected?**_

The issue is if for some reason you also want to use the following:
`let session = try await supabase.auth.signInWithOAuth(
  provider: .google
) `

`try await supabase.auth.linkIdentity(provider: .google)
`

To use the above two code snipped you need to use an OAuth 2.0 Client IDs from your Google Cloud console that _**is not an iOS client**_ 

If you use an iOS client you get the error:
`Google 400 Error: invalid request Custom scheme URIs are not allowed for 'Web' client type`

But if you update the OAuth client ID and secret on Supabase Dashboard > Authentication > Providers to be a web OAuth client then your GoogleSignIn returns the error:
`Unacceptable audience in id_token `

I hope this makes sense, happy to expand on any of the above. 

To help understand why it is important, when using Anonymous users there seems to be no way besides using the above conflicting method to create and link an account if the user has registered anonymously.

**Comment by rizhangdev** [comment] 2024-08-18 06:02
I'm seeing this error and I did set my Web client Id on my supabase dashboard. I'm sure I'm doing something wrong but it is not obvious what it is.

**Comment by elyobo** [comment] 2024-08-19 21:16
It's maddening how unclear the docs are on what seems like a very common (possibly *the most common*) scenario

* want to support Google sign in across iOS and Android (and, maybe less common, also web)
* want to develop using local supabase

I'm not sure that this is even possible; it's definitely unclear whether the additional client IDs are supported locally, and if so, how to set them.

**Comment by sunhohong** [comment] 2024-09-25 12:12
@elyobo I had the exact same issue and found that while the Supabase remote console allows adding Google additional client IDs, there's no clear guidance or solution for doing this in a local Supabase setup.

To cut to the chase: you can resolve this issue by adding the `SUPABASE_EXTERNAL_GOOGLE_ADDITIONAL_CLIENT_IDS` environment variable, similar to how you add the Google additional client ID in the Supabase remote console.

I spent quite a while looking through the `config.toml` for local Supabase but couldn't find anything there. However, after checking the source code, I figured that adding this environment variable should work, and indeed it does.

Just set it in your local environment like this:

```bash
SUPABASE_EXTERNAL_GOOGLE_ADDITIONAL_CLIENT_IDS="your_google_additional_client_id"
```

This will allow your local setup to function similarly to how it does in the remote console when dealing with Google sign-ins.

**Comment by grdsdev** [comment] 2024-09-25 13:18
Thanks @sunhohong I'll make sure to include this in the docs.

**Comment by elyobo** [comment] 2024-10-07 22:08
@sunhohong I came to the eventual conclusion that it didn't matter because the only client ID that supabase actually _sees_ is the web client ID; the Android one isn't needed in your app at all (it does need to exist, and with a valid SHA1, in the same project) and the iOS one is needed in the app but not in Supabase, so I have local auth working in iOS and Android using only the web client ID and didn't need to use any more.

**Comment by shubyaa** [comment] 2024-10-15 05:47
Hi, please do make sure that if the app's package name is changed, you might need to create or replace the ID again for your app.

**Comment by Foixa** [comment] 2024-10-31 15:31
Any solution?

**Comment by moshkla** [comment] 2024-11-17 22:19
[Solved]

<img width="856" alt="Screenshot 2024-11-18 at 12 15 36 AM" src="https://github.com/user-attachments/assets/342c397a-f8b1-4759-8563-1c9c5ca0ecdf">

You need to add client Ids from credentials Google Cloud Apis separated with ( , )

<img width="1152" alt="Screenshot 2024-11-18 at 12 17 07 AM" src="https://github.com/user-attachments/assets/426c1c68-5c90-481e-9d45-10798491960b">

**Comment by grdsdev** [comment] 2024-12-10 12:07
To summarise, you have to add both Web Client ID and iOS Client ID under the _Cliend IDs_ in the Supabase Dashboard separated with a comma, that way both OAuth (Identity linking) and ID token methods should work.

I've pushed a fix to the documentation to make this clearer, https://github.com/supabase/supabase/pull/31044

Thank you all for the help with this one.

**Closed by grdsdev** 2024-12-10 12:07 UTC
Labels: bug

**Comment by bqubique** [comment] 2024-12-29 10:52
> To summarise, you have to add both Web Client ID and iOS Client ID under the _Cliend IDs_ in the Supabase Dashboard separated with a comma, that way both OAuth (Identity linking) and ID token methods should work.
> 
> I've pushed a fix to the documentation to make this clearer, [supabase/supabase#31044](https://github.com/supabase/supabase/pull/31044)
> 
> Thank you all for the help with this one.

Thank you for reflecting it, but the thing is there is an official Supabase video from @dshukertjr where he implements Google Sign in with the old method, w/o adding all the tokens in the dashboard. Could you update that video, or any other guides that are out there? 

Thank you.

**Comment by dshukertjr** [comment] 2025-01-01 11:43
@bqubique 
If you are talking about [this video](https://youtu.be/utMg6fVmX0U?si=HYfaXZZnRroLwU0J), it's for Flutter, and the steps in the video are still valid. 

When Supabase completes the sign-in on the server side, it only uses one client ID, and it shouldn't need multiple IDs registered to complete the sign-in. I believe the missing step for people here is to [configure backend authentication](https://developers.google.com/identity/sign-in/ios/start-integrating). 

@grdsdev When you have time, could you verify that Google sign-in works with only the web client ID and no iOS client ID in the Supabase dashboard once completing the [configure backend authentication](https://developers.google.com/identity/sign-in/ios/start-integrating) step with web client ID

**Comment by JihongGan** [comment] 2025-02-17 10:51
For local development, it worked for me to set `client_id` to be the comma seperated list of client IDs

**Comment by projectninjatech** [comment] 2025-03-04 16:35
> [Solved]
> 
> <img alt="Screenshot 2024-11-18 at 12 15 36 AM" width="856" src="https://private-user-images.githubusercontent.com/25544294/387009665-342c397a-f8b1-4759-8563-1c9c5ca0ecdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDExMDYyMDYsIm5iZiI6MTc0MTEwNTkwNiwicGF0aCI6Ii8yNTU0NDI5NC8zODcwMDk2NjUtMzQyYzM5N2EtZjhiMS00NzU5LTg1NjMtMWM5YzVjYTBlY2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA0VDE2MzE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YWRkYzc5ODBlYmRmNmU1NGE3OTBiYTQ4ZWY1ZTY3MDdmOWEzMTZmOTJhNzlmNzE1ZGM0NTg4NTIzZDA0NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lZVbfymIGqM2ekATfPXZ_jRXe2V6vtYeNSb4gAYdz5g">
> You need to add client Ids from credentials Google Cloud Apis separated with ( , )
> 
> <img alt="Screenshot 2024-11-18 at 12 17 07 AM" width="1152" src="https://private-user-images.githubusercontent.com/25544294/387009914-426c1c68-5c90-481e-9d45-10798491960b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDExMDYyMDYsIm5iZiI6MTc0MTEwNTkwNiwicGF0aCI6Ii8yNTU0NDI5NC8zODcwMDk5MTQtNDI2YzFjNjgtNWM5MC00ODFlLTlkNDUtMTA3OTg0OTE5NjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA0VDE2MzE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZjM3NjM5OTBmZWUxMWE4ZmY3NWYyMjIxMTQzNjdlOTFhYTRlZWUxNGI5YzJlYTVmMWVmYmI3NjVkNzIyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MAk-Cos_5Bir90knoCb3j3U9yzXe2_vk-WNX0xEmMQI">

This works perfectly copy the android client id and web client id and paste in supabse google auth client id separated by , like this 115929535401-vrh4jjoockhuk1urfs8.apps.googleusercontent.com,115929535401-2s2ovnh502nvhnn97n.apps.googleusercontent.com

**Comment by bqubique** [comment] 2025-04-22 11:30
> > [Solved]
> > <img alt="Screenshot 2024-11-18 at 12 15 36 AM" width="856" src="https://private-user-images.githubusercontent.com/25544294/387009665-342c397a-f8b1-4759-8563-1c9c5ca0ecdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDExMDYyMDYsIm5iZiI6MTc0MTEwNTkwNiwicGF0aCI6Ii8yNTU0NDI5NC8zODcwMDk2NjUtMzQyYzM5N2EtZjhiMS00NzU5LTg1NjMtMWM5YzVjYTBlY2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA0VDE2MzE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YWRkYzc5ODBlYmRmNmU1NGE3OTBiYTQ4ZWY1ZTY3MDdmOWEzMTZmOTJhNzlmNzE1ZGM0NTg4NTIzZDA0NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lZVbfymIGqM2ekATfPXZ_jRXe2V6vtYeNSb4gAYdz5g">
> > You need to add client Ids from credentials Google Cloud Apis separated with ( , )
> > <img alt="Screenshot 2024-11-18 at 12 17 07 AM" width="1152" src="https://private-user-images.githubusercontent.com/25544294/387009914-426c1c68-5c90-481e-9d45-10798491960b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDExMDYyMDYsIm5iZiI6MTc0MTEwNTkwNiwicGF0aCI6Ii8yNTU0NDI5NC8zODcwMDk5MTQtNDI2YzFjNjgtNWM5MC00ODFlLTlkNDUtMTA3OTg0OTE5NjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA0VDE2MzE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZjM3NjM5OTBmZWUxMWE4ZmY3NWYyMjIxMTQzNjdlOTFhYTRlZWUxNGI5YzJlYTVmMWVmYmI3NjVkNzIyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MAk-Cos_5Bir90knoCb3j3U9yzXe2_vk-WNX0xEmMQI">
> 
> This works perfectly copy the android client id and web client id and paste in supabse google auth client id separated by , like this 115929535401-vrh4jjoockhuk1urfs8.apps.googleusercontent.com,115929535401-2s2ovnh502nvhnn97n.apps.googleusercontent.com

What worked for me was putting ONLY web and macOS Client IDs (this works for iOS as well, without having to add iOS's separate client ID) in Supabase Dashboard->Sign In / Sign Up-> Google -> Client IDs.
When I inserted Android's client ID, I ended up with  `400: redirect_uri_mismatch`.
