### ISSUE TITLE
support linkIdentity

### ISSUE THREAD

**Issue by johndpope** [supabase/supabase-swift#256] opened 2024-03-06 23:29 UTC
as per https://github.com/supabase/gotrue/issues/313

we need similar capabilities in swift / mobile 
```

// assume user is already logged in and authenticated

// link the current user to a google identity
// this works very similar to signInWithOAuth() and will redirect the user to google to complete the oauth flow 
// once the oauth flow has been completed, the user will be redirected back to the app with the identity linked
const { data, error } = await supabase.auth.linkIdentity({ provider: 'google' })

// fetch all identities linked to the current user
const { data: { identities } } = await supabase.auth.getUserIdentities()

const googleIdentity = identities.find(identity => identity.provider === 'google')

// unlink an identity
await supabase.auth.unlinkIdentity(googleIdentity)


```

**Comment by grdsdev** [comment] 2024-03-07 08:17
Hi @johndpope 

Thanks for opening this issue, but it is a duplicate of https://github.com/supabase-community/supabase-swift/issues/193

We're planning to add support for it in the next couple of weeks.

So I'll be closing this in favor of the other one.

**Closed as not planned by grdsdev** 2024-03-07 08:17 UTC
Labels: enhancement
