### ISSUE TITLE
OAuth Login with Auth Provider Example

### ISSUE THREAD

**Issue by toystorynova** [supabase/supabase-swift#48] opened 2022-11-10 06:38 UTC
# Feature request

I see in the gotrue RC pr the Google OAuth example was removed - 
https://github.com/supabase-community/gotrue-swift/pull/37/files#diff-5040cbf573fdc1b4fc2384e97402e4a832b40b22e33b3ff33fd0568db8e35ab1

This was referenced in a few issues - 
https://github.com/supabase-community/supabase-swift/issues/39#issuecomment-1237818305
https://github.com/supabase-community/supabase-swift/issues/32#issuecomment-1168798055
(FWIW, I was never able to get that example working.. it would never redirect back to my app)

Found another request for it 
https://www.reddit.com/r/Supabase/comments/xbjkt5/guidance_needed_in_relation_to_supabase_auth_swift/

It's also being talked about in the community Discord channel (#swift) for something like this (?)

I'd also like to add that I'm new to Swift and would be interested in a full blown example app I could clone and learn from... with auth, realtime, and databasing. There's a lot of examples on the Supabase website, just none in Swift!

**Comment by maail** [comment] 2023-02-22 04:37
Hey @toystorynova,

We've updated the Read Me with examples for OAuth (with Google Auth example)  and Database queries. Please take a look and let us know if this satisfies your needs. 

Then we can close this issue.

**Comment by thomasefbland** [comment] 2023-02-23 02:07
Having some issues implementing the GoTrue login section. Perhaps I am missing something?
```
let client = GoTrueClient(url: URL(string: "{my url}")!, headers: ["apikey": "{my key}"])

    var body: some View {
        VStack {
            Button {
                Task {
                    do {
                        url = try await client.getOAuthSignInURL(provider: Provider.google, redirectTo: URL(string: "app.mydocket://login-callback")!)
//                        try await Task.sleep(nanoseconds: 2_000_000_000)
                        showSafari = true
                    } catch {
                        print("### Google Sign in Error: \(error)")
                    }
                }
            } label: {
                Text("Continue with Google")
            }
        }.sheet(isPresented: $showSafari) {
            SafariView(url: url)
        }
```
There's a warning at `try await client.getOAuthSignInURL` No 'async' operations occur within 'await' expression

When the modal opens, it opens to this 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/17321491/220806120-12c4fe1e-c4a8-4779-a0e5-ac9303d5cd1e.png">

Any advice? I know I am deviating a bit already from the example by using
```
struct SafariView: UIViewControllerRepresentable {
    
    let url: URL
    
    func makeUIViewController(context: UIViewControllerRepresentableContext<SafariView>) -> SFSafariViewController {
        return SFSafariViewController(url: url)
    }

    func updateUIViewController(_ uiViewController: SFSafariViewController, context: UIViewControllerRepresentableContext<SafariView>) {

    }
    
}
```
rather than SafariViewController

**Comment by iamlouislab** [comment] 2023-02-27 15:44
A small misunderstanding of the examples is the issue here. You're supposed to use a supabase client and not a GoTrue client. I assume you're using the GoTrue client as no getOAuthSignInURL method is available on the supabase client. The issue is that the examples use client.getOAuthSignInURL instead of client.auth.getOAuthSignInURL.

I submitted a pull request to fix this error in the example here: https://github.com/supabase-community/supabase-swift/pull/65

**Comment by maail** [comment] 2023-03-05 03:36
@toystorynova I had this issue recently as well after I changed my callback URL, so the error message might not be exactly showing the issue you are having. 

Couple of things to check:

-  Make sure the callback URL is properly added to your Info.plist. If it's app.mydocket://login-callback, add app.mydocket as well.

<key>CFBundleURLSchemes</key>
<array>
                <string>app.mydocket</string>
		<string>app.mydocket://login-callback</string>
</array>

- Double check the logic callback URL set on Supabase and it should match your callback. 

Clear your cache and try again and let me know.

**Closed as completed** 2023-03-07 23:33 UTC
Labels: enhancement
